export TERM="xterm-256color"
POWERLEVEL9K_MODE='awesome-fontconfig'

POWERLEVEL9K_FOLDER_ICON=$'\uF07C '
POWERLEVEL9K_HOME_SUB_ICON=$'\uF015 '
POWERLEVEL9K_DIR_PATH_SEPARATOR=$' \uE0B1 '

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='178'
POWERLEVEL9K_NVM_BACKGROUND="238"
POWERLEVEL9K_NVM_FOREGROUND="green"
#POWERLEVEL9K_NVM_BACKGROUND="black"
#POWERLEVEL9K_NVM_FOREGROUND="249"
#POWERLEVEL9K_NVM_VISUAL_IDENTIFIER_COLOR="green"

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="green"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="015"
POWERLEVEL9K__ROOT_INDICATOR_FOREGROUND="red"

POWERLEVEL9K_TIME_BACKGROUND='255'
#POWERLEVEL9K_COMMAND_TIME_FOREGROUND='gray'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir dir_writable vcs)
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs command_execution_time time)
POWERLEVEL9K_SHOW_CHANGESET=true

HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
	
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX=" ❯ "
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX_FOREGROUND="cyan"
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true



# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Allow local customizations in the ~/.zshrc_local_before file
if [ -f ~/.zshrc_local_before ]; then
    source ~/.zshrc_local_before
fi

# Aliases
source ~/.dotfiles/zsh/aliases.zsh

# Zsh has a spelling corrector
setopt CORRECT

# if you do a 'rm *', Zsh will give you a sanity check!
setopt RM_STAR_WAIT

# want your terminal to support 256 color schemes? I do ...
#export TERM="xterm-256color"

export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

export CHEATCOLORS=true

# allows you to type Bash style comments on your command line
# good 'ol Bash
setopt interactivecomments

# beeps are annoying
setopt NO_BEEP

#To save every command before it is executed (this is different from bash's history -a solution):
setopt inc_append_history
#
##To retrieve the history file everytime history is called upon.
setopt share_history

export JAVA_HOME="/usr/lib/jvm/jdk1.8.0_121/"
export PATH=$PATH:$JAVA_HOME/bin

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/tkaramp/.sdkman"
[[ -s "/home/tkaramp/.sdkman/bin/sdkman-init.sh" ]] && source "/home/tkaramp/.sdkman/bin/sdkman-init.sh"
